language: node_js

node_js:
  - '0.10'
  - '0.11'

script:
  - npm run-script lint
  - npm run-script lint-test
  - npm run-script cover

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
